### ISSUE TITLE
Create an internal publishing mechanism

### ISSUE THREAD

**Issue by mbland** [18F/pages-server#9]
Per a discussion with @hollyallen, we want to support a publishing mode for private repos that can generate both internal and external versions of a piece of documentation.

Some early implementation notes:

We can easily set up an authenticated internal host, https://pages-internal.18f.gov/, that is authenticated in the same way as https://pages-staging.18f.gov/. (Or we can configure those auth options dfferently, if we wanted.)

I'm thinking sites that want to publish both internally and externally need to contain a `_config_18f_pages_internal.yml` file that contains only an `internal: true` entry. Then internal-only content can be wrapped with `{% if site.internal %}...{% endif %}`. The server can then generate both internal and public versions from a single `18f-pages` branch.

Making entire pages private will require that the repo contain a `_config_18f_pages_exclude.yml` file with a [Jekyll `exclude:` configuration directive](http://jekyllrb.com/docs/configuration/) identifying particular pages or directories. If the repo contains this file, any public builds will automatically include this configuration to ensure those pages are not in the output.

**Comment by mbland** [comment]
This is what I'm currently planning in terms on implementation steps:
- [x] Add a new `internalSiteDir:` property to the `builders:` config property
- [x] Raise errors if:
  - `_config_internal.yml` is present but there is no `internalSiteDir` defined for the `builder:`
  - `_config_external.yml` is present without a corresponding `_config_internal.yml` file
- [x] If the project has a `_config_internal.yml` file:
  - [x] Publish an internal version
  - [x] Publish a public version, including the `_config_external.yml` file if present
- [x] Launch the `pages-internal.18f.gov` host

I decided on having these `_config_internal.yml` and `_config_external.yml` files for a couple of reasons:
- The presence of `_config_internal.yml` is a clear signal that this site has different internal- and external-facing versions.
- The names don't contain "18F Pages" in any way, as the concept is orthogonal to the organization hosting the site.
- Developers can view the different sites via the common Jekyll mechanism (which can be wrapped in a [`./go` script](https://github.com/18F/go_script/), of course):

```
$ bundle exec jekyll serve --config _config.yml,_config_internal.yml
$ bundle exec jekyll serve --config _config.yml,_config_external.yml
```

I thought about having some more stringent checks on the content of `_config_internal.yml` and `_config_external.yml`, e.g. the former MUST contain `internal: true` and the latter MUST contain a nonempty `exclude:` property, but decided to allow some flexibility there.

I was thinking about how to have an internal-only site, and it seems the best way to do that is to require those sites to have an `18f-pages-internal` branch (for example) in concert with a `builder:` configured specifically for that branch. The `generatedSiteDir` for this builder can be the same as the `internalSiteDir` for another builder, which is then served by a single authenticated server.

**Comment by mbland** [comment]
This is pretty much done between #10, #11, and #12. When those are in, I'll cut a new npm and deploy to `pages-internal.18f.gov`.

**Comment by mbland** [comment]
Though this is pretty much done, I'm going to leave it open until we have content actually published to pages-internal.18f.gov.

**Comment by fureigh** [comment]
So glad this exists! It sounds like a good fit for the forthcoming [Evaluating Candidates guide](https://github.com/18F/evaluating-candidates-guide/). Its content is still in progress, but I'll report back after deployment. cc @hestherchang

**Comment by fureigh** [comment]
Closing because we now have content published to https://pages-internal.18f.gov/evaluating-candidates-guide/. Thanks, @mbland!

**Comment by mbland** [comment]
_Sweeet..._ :smile:
